# Generated by Django 4.2.5 on 2023-10-24 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geoGuess", "0002_challenge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge", old_name="latitutde", new_name="latitude",
        ),
    ]
