# Generated by Django 4.2.5 on 2023-11-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoGuess', '0004_guess_delete_location_challenge_approve_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='numOfAttempts',
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoGuess.challenge')),
            ],
        ),
    ]
