# Generated by Django 4.2.5 on 2023-11-05 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoGuess', '0004_guess_delete_location_challenge_approve_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='approval_feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='guess',
            name='distanceFromAnswer',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='guess',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
