# Generated by Django 4.2.5 on 2023-11-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoGuess', '0005_remove_guess_numofattempts_dailychallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='guess',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
