# Generated by Django 4.2.5 on 2023-11-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoGuess', '0006_guess_latitude_guess_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='approval_feedback',
            field=models.TextField(default=''),
        ),
    ]
