# Generated by Django 4.2.5 on 2023-11-05 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoGuess', '0007_challenge_approval_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='distanceFromAnswer',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='Distance must be greater than or equal to 0')]),
        ),
        migrations.AlterField(
            model_name='guess',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Score must be greater than or equal to 0')]),
        ),
    ]
